#hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000
server:
  port: 8091
eureka:
  client:
    serviceUrl:
      defaultZone: http://106.14.116.177:8001/eureka/
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号
security:
  oauth2:
    client:
      access-token-uri:http://localhost:8090/oauth/token
      user-authorization-uri: http://localhost:8090/oauth/authorize
      client-id: cloud
      client-secret: cloud
    resource:
      user-info-uri: http://localhost:8090/users/current
      prefer-token-info: false
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service
        uri: http://localhost:8005
        predicates:
          - Path=/user/**
        filters:
        - StripPrefix= 1
      - id: cms-service
        uri: lb://cms-service
        predicates:
        - Path=/cms/**
        filters:
        - StripPrefix= 1


