server:
    port: 8003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
  instance:
      hostname: ${spring.cloud.client.ip-address}
      instance-id: ${spring.cloud.client.ip-address}:${server.port}
      prefer-ip-address: true
      status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号
#security:
#  basic:
#    enabled: false

#spring
spring:
  #devtools:
  #  restart:
   #   enabled: false

  # H2 DATABASE CONFIG
  application:
    name: cms-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #schema: classpath:/db/schema-h2.sql
    #data: classpath:/db/data-h2.sql
    url: jdbc:mysql://106.14.116.177:3306/clouddo?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  servlet:
    multipart:
      enabled: true
      max-file-size: 1Mb
      max-request-size: 100Mb





#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ocean.clouduser.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

