server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://106.14.116.177:8001/eureka/
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号
#spring
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  application:
    name: oauth-service
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://106.14.116.177:3306/clouddo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 123456
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 2
      min-idle: 2
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter.commons-log.connection-logger-name: stat,wall,log4j
      filter.stat.log-slow-sql: true
      filter.stat.slow-sql-millis: 2000
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      use-global-data-source-stat: true
      filter:
        stat:
          enabled: true
          slow-sql-millis: 5000
      # 合并多个DruidDataSource的监控数据
  redis:
    host: 106.14.116.177
    port: 6379
###feign 默认关闭熔断，请看HystrixFeignConfiguration
feign:
  hystrix:
    enabled: true
access_token:
  store-jwt: false
